services:
  mnnl-api:
    image: ghcr.io/${GITHUB_OWNER}/mnnl-api:latest
    container_name: mnnl-api
    restart: unless-stopped
    env_file: apps/api/.env
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - app_network

  mnnl-web:
    image: ghcr.io/${GITHUB_OWNER}/mnnl-web:latest
    container_name: mnnl-web
    restart: unless-stopped
    env_file: apps/web/.env
    ports:
      - "127.0.0.1:3000:3000"


networks:
  internal:
  app_network:
    external: true
