services:
  mnnl-api:
    image: ghcr.io/${GITHUB_OWNER}/mnnl-api:latest
    container_name: mnnl-api
    restart: unless-stopped
    env_file: apps/api/.env
    networks:
      - internal
      - app_network

  mnnl-web:
    image: ghcr.io/${GITHUB_OWNER}/mnnl-web:latest
    container_name: mnnl-web
    restart: unless-stopped
    env_file: apps/web/.env
    networks:
      - internal


networks:
  internal:
  app_network:
    external: true
